version: '3.2.2'

services:
  db:
    image: "postgres:15.2"
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mahmouddabbbagh
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/matrix

volumes:
  postgresql-data:
  bundle:
